app/assets/typescript/index.ts
including a fix for setup moves
=> Special action buttons

src/components/Building.vue, src/components/Commands.vue, src/components/PlayerInfo.vue
Added buildings and gaiaformers
Change color for planets with building, mine as triangle, so triangle -> square+triangle -> square
=> PlayerInfo and map readability

src/components/Commands.vue, src/components/MoveButton.vue, src/components/PlayerInfo.vue, src/data/factions.ts, src/data/planets.ts
including different shadows per faction color and a nitpick
=> faction info

src/components/Commands.vue, src/components/PlayerInfo.vue, src/data/factions.ts
=> Additional faction info

src/components/Commands.vue
=> Advance single research

src/components/Commands.vue, src/components/SpaceHex.vue
Solves #50 and improves every faction
=> Fed strokes for factions and clean custom fed

src/components/Game.vue
=> turnOrder description

src/components/Planet.vue, src/components/ResearchTile.vue, src/components/Resource.vue, src/components/Token.vue, src/data/planets.ts
Changed the colors for better readability.
Also modified tokens and resources.
I'll complete resources with descriptions for terraforming and reachability
New version:
Previous version:
=> Colors and resource imrpovements

package.json, src/components/Building.vue, src/components/Commands.vue, src/components/Game.vue, src/components/Planet.vue, src/components/ResearchTile.vue, src/components/Resource.vue
I've aligned colors in playersInfo.
Complete resource descriptions
I've also added the lostPlanet in the researchTrack. Even though it's not that good.
=> resources and color alignment

src/components/BoardAction.vue, src/components/Game.vue, src/data/event.ts
Added cost description and aligned the eventDesc at the general wording in the official rules
=> Improved BoardAction descriptions

src/components/Game.vue
This implements the ability to replay a game move by move. I need help on the formatting, but it works just fine.
=> Ability to replay a game

src/components/FinalScoringTile.vue, src/components/Resource.vue
With culture levels in the expansion reaching 20+, this feels needed
=> Change of style for final scoring tile

package.json, src/components/Game.vue, src/components/PlayerBoard/BuildingGroup.vue, src/components/PlayerBoard/Info.vue, src/components/PlayerBoard/PowerBowls.vue, src/components/PlayerInfo.vue, src/components/ResearchTile.vue, src/components/Resource.vue, src/registerServiceWorker.ts, src/store.ts
Before:
After:
Will need to squash when merging.
=> New playerinfo

package.json, src/components/Commands.vue, src/components/Game.vue
this has been requested several time. I've also added the ability to see the current move in replayMode
=> endTurn and final Pass confirmation

.vscode/launch.json, src/components/AdvancedLog.vue, src/components/Commands.vue, src/components/MoveButton.vue, src/components/TurnOrder.vue
Basic implementation to support auction phase.
I would prefer to have full names under the Turn Order factions.
Missing the ability to bid more than  +1
=> Auction support in viewer

src/components/Commands.vue, src/components/MoveButton.vue, src/components/PlayerBoard/Info.vue, src/components/TurnOrder.vue
I've also added the bid amount in the playerInfo
=> code to support bid 0 and revised setup

src/components/Commands.vue, src/components/MoveButton.vue, src/data/index.ts
confirmation after selection and display properties
=> Better Boosters

src/components/Filters.vue
Giving the buildings a name is a tad more difficult, so I think two seperate PRs are better.
=> Grey buildings are darker and white buildings are more bright

src/components/PlayerBoard/Info.vue
this prevents unnecessary scrolling up and down
=> show research progress in player info as well

src/components/FactionWheel.vue
so you don't have to scan the map to see if there are any planets (e.g. gaia) left
=> display remining planet count in faction wheel

src/components/Game.vue, src/components/Planet.vue, src/components/PlayerBoard/Info.vue, src/components/ResearchTile.vue, src/store.ts
added option for accessible space map for color blind
it needs an option to activate it
=> accessible_space_map

src/components/ResearchBoard.vue, src/components/Resource.vue
=> show free resource conversion

src/components/PlayerBoard/Info.vue, src/components/ResearchBoard.vue, src/components/Resource.vue
=> fix 0 resource (was showing nothing instead)
